### PR TITLE
Feat/prolog user output

### PR DESCRIPTION
**Pull request by ccamel**
Implements #326.

-----

Example:

```
$ okp4d query logic ask "write('Mind blowing'), put_char('!')." ""
answer:
  has_more: false
  results:
  - substitutions: []
  success: true
  variables: []
gas_used: "2237"
height: "27"
user_output: Mind blowing!
```

### CODE REVIEW

**Review by amimart — APPROVED** [review]
Looks good to me!

Glad to see a circular buffer by the way, love that 😉

**Comment by ccamel** [comment]
@amimart This one will impact [cw-law-stone](https://github.com/okp4/contracts/tree/main/contracts/cw-law-stone) no?

**Comment by amimart** [comment]
> @amimart This one will impact [cw-law-stone](https://github.com/okp4/contracts/tree/main/contracts/cw-law-stone) no?

I don't see why?

**Review by bdeneux — APPROVED** [review]
Looks great ! 😊 

> @amimart This one will impact [cw-law-stone](https://github.com/okp4/contracts/tree/main/contracts/cw-law-stone) no?

I don't see why too...

**Comment by ccamel** [comment]
> > @amimart This one will impact [cw-law-stone](https://github.com/okp4/contracts/tree/main/contracts/cw-law-stone) no?
> 
> I don't see why?

Was about the addition of the extra field `user_output` in the proto response, but on the one hand it's not a breaking change so no impact and on the other hand, I guess it's irrelevant for the `cw-law-stone`. right for you? 🤓

**Pull request merged**
