### PR TITLE
version bumps

### PR DESCRIPTION
**Pull request by faddat**
Note: this is state breaking and if you've already 
upgraded to 47, don't distribute this to the 
validator set.  

If you have not upgraded, this should be favorable 
to the previous setup :)

### CODE REVIEW

**Review by amimart — CHANGES_REQUESTED** [review]
We haven't upgraded yet so this is great.

Could you just bump the go version to `1.20` in the `Dockerfile` as well please?

**Review by amimart — APPROVED** [review]
@faddat I took the liberty to update the go version to `1.20` everywhere and update the generated documentation, I hope you don't mind :)

Thank you for your help 🙏

**Review by ccamel — APPROVED** [review]
:+1: Thx

**Comment by amimart** [comment]
@ccamel @bdeneux The Go linter doesn't pass but I think it's more a cache issue, I propose to merge it and we'll see.

**Review by bdeneux — APPROVED** [review]
Nice, thanks 🙏

**Pull request merged**
