### PR TITLE
style: update readme and okp4 banner

### PR DESCRIPTION
**Pull request by jeremylgn**
Self explanatory.

### CODE REVIEW

**Review by ccamel — CHANGES_REQUESTED** [review]
If you now point to the banner hosted in `okp4/.github`, you can safely delete banners from this repo in the `etc` folder.

**Comment by jeremylgn** [comment]
> If you now point to the banner hosted in `okp4/.github`, you can safely delete banners from this repo in the `etc` folder.

Done :ballot_box_with_check:

**Review by MdechampG — APPROVED** [review]

**Review by ccamel — CHANGES_REQUESTED** [review]
The banner doesn't look good because it's narrower than the previous version and doesn't fill the entire width of the page. To improve this, I'd recommand to modify the HTML attributes of the image to make it display at full width and see how it looks. As this project is the most significant one, it is essential that the `README.md` page is perfect. :relieved: 

image

**Comment by jeremylgn** [comment]
> The banner doesn't look good because it's narrower than the previous version and doesn't fill the entire width of the page. To improve this, I'd recommand to modify the HTML attributes of the image to make it display at full width and see how it looks. As this project is the most significant one, it is essential that the `README.md` page is perfect. relieved
> image

Done :heavy_check_mark:

**Review by ccamel — COMMENTED** [review]
LGTM! :+1:

**Review by ccamel — APPROVED** [review]

**Review by fredericvilcot — APPROVED** [review]
👍

**Pull request merged**
